[package]
name = "R_CONSOLE_HOST"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "R_CONSOLE_HOST"
path = "src/main.rs"

[dependencies]
libc = "0.2"
libloading = "0.8"
windows-sys = { version = "0.61", features = [
  "Win32_Foundation",
  "Win32_Globalization",
  "Win32_System_Console",
  "Win32_System_Threading",
] }
